version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - github_actions

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - ruby

  # These are not meant to be automatically accepted
  # because they're templated files, however this will
  # give us a way to be automatically notified when there
  # are upstream changes to roll into our own templates.
  - package-ecosystem: docker
    directory: core/noble
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: core/jammy
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: core/bionic
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/8
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/10
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/12
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/14
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/16
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/18
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/20
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/22
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/24
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: node/25
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/2.4
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/2.5
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/2.6
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/2.7
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/3.0
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/3.1
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/3.2
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/3.3
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only

  - package-ecosystem: docker
    directory: ruby/3.4
    schedule:
      interval: daily
    labels:
      - dependencies
      - do-not-merge
      - docker
      - notification-only
